<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include
        filename="$(find mobile_manipulator_description)/urdf/external/wheels.xacro"/>

    <xacro:property name="base_x_size" value="0.6200000"/>
    <xacro:property name="base_y_size" value="0.585000"/>
    <xacro:property name="base_z_size" value="0.235000"/>

    <xacro:property name="wheelbase" value="0.34"/>
    <xacro:property name="track" value="0.37910"/>

    <xacro:property name="castor_length" value="0.002"/>
    <xacro:property name="castor_radius" value="0.03724"/>

    <xacro:property name="wheel_vertical_offset" value="-0.082"/>
    <xacro:property name="castor_offset" value="0.03"/>

    <xacro:macro name="tracer" params="prefix">
        <link name="${prefix}base_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <geometry>
                    <mesh
                        filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <geometry>
                    <mesh
                        filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae"/>
                </geometry>
            </collision>
        </link>

        <link name="${prefix}inertial_link">
            <inertial>
                <origin xyz="0.015 0.0231316650320557 0"/>
                <mass value="132.3898489950015"/>
                <inertia ixx="0.185196122711036"
                    ixy="4.30144213829512E-08"
                    ixz="5.81037523686401E-08"
                    iyy="0.364893736238929"
                    iyz="-0.000386720198091934"
                    izz="0.223868521722778"/>
            </inertial>
        </link>

        <joint name="${prefix}inertial_link_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="${prefix}base_link"/>
            <child link="${prefix}inertial_link"/>
        </joint>

        <xacro:wheel name="${prefix}wheel_left" parent="${prefix}base_link">
            <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
        </xacro:wheel>
        <xacro:wheel name="${prefix}wheel_right" parent="${prefix}base_link">
            <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
        </xacro:wheel>

        <xacro:caster_wheel name="${prefix}castor_wheel_fl" parent="${prefix}base_link">
            <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0680886}"
                rpy="${radians(-90)} 0 0"/>
        </xacro:caster_wheel>
        <xacro:caster_wheel name="${prefix}castor_wheel_fr" parent="${prefix}base_link">
            <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0680886}"
                rpy="${radians(-90)} 0 0"/>
        </xacro:caster_wheel>
        <xacro:caster_wheel name="${prefix}castor_wheel_rl" parent="${prefix}base_link">
            <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0680886}"
                rpy="${radians(-90)} 0 0"/>
        </xacro:caster_wheel>
        <xacro:caster_wheel name="${prefix}castor_wheel_rr" parent="${prefix}base_link">
            <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0680886}"
                rpy="${radians(-90)} 0 0"/>
        </xacro:caster_wheel>
    </xacro:macro>
</robot>
