<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="name parent *joint_pose">
        <link name="${name}">
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="6"/>
                <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/tracer_wheel.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/tracer_wheel.dae"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_joint" type="continuous">
            <xacro:insert_block name="joint_pose"/>
            <parent link="${parent}"/>
            <child link="${name}"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="caster_wheel" params="name parent *joint_pose">
        <link name="${name}_link">
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/castor_joint.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/castor_joint.dae"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_link_joint" type="continuous">
            <xacro:insert_block name="joint_pose"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
        </joint>

        <link name="${name}">
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="0.3131" ixy="0" ixz="0" iyy="0.3131" iyz="0" izz="0.1361"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/castor.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://tracer_description/meshes/castor.dae"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_joint" type="continuous">
            <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0"/>
            <parent link="${name}_link"/>
            <child link="${name}"/>
            <axis xyz="0 0 1" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
</robot>
